var time_start = new Array(8,7,6,6,6,6,6,7,7,7,7,8)
var time_end = new Array(17,18,20,21,21,22,22,21,20,19,17,17)
var sollMonth = new Array(2,6,9,11,11,13,13,12,10,6,4,3)
var SollYearKWP=890
var AnzahlWR = 5
var MaxWRP=new Array(AnzahlWR)
MaxWRP[0]=new Array(33700,270000,4850000,37500000)
MaxWRP[1]=new Array(36500,290000,5250000,40500000)
MaxWRP[2]=new Array(131800,1055000,2300000,18000000)
MaxWRP[3]=new Array(126200,1010000,1500000,11500000)
MaxWRP[4]=new Array(550000,2640000,81850000,982000000)
var WRInfo = new Array(AnzahlWR)
WRInfo[0]=new Array("SUN2000-30KTL-M","0",30600,1,"WR 3",4,null,null,30000,null,232,0,1,1000,null)
WRInfo[0][6]=new Array("Str 37 SO","Str 38 NW","Str 39 SO","Str 40 NW")
WRInfo[0][7]=new Array(1,2,1,2)
WRInfo[0][9]=new Array(7650,7650,7650,7650)
WRInfo[0][16]=1
WRInfo[0][17]=1
WRInfo[1]=new Array("SUN2000-30KTL-M","0",33150,2,"WR 4",4,null,null,30000,null,232,0,1,1000,null)
WRInfo[1][6]=new Array("Str 33 NW","Str 34 SO","Str 35 NW","Str 36 SO")
WRInfo[1][7]=new Array(2,1,2,1)
WRInfo[1][9]=new Array(8075,8075,8500,8500)
WRInfo[1][16]=1
WRInfo[1][17]=1
WRInfo[2]=new Array("U","2",500000,1,"Netzzähler",0,null,null,0,null,84,2,0,1000,null)
WRInfo[2][14]=8
WRInfo[2][15]=0
WRInfo[2][16]=4
WRInfo[2][17]=1
var HPTitel="[Anlagenbezeichnung]"
var HPBetreiber="[Betreibername]"
var HPEmail="[Kontakt-Emailadresse]"
var HPStandort="[Standort der Anlage]"
var HPModul="[Beschreibung der Module und Hersteller]"
var HPWR="[Wechselrichterbezeichnung und Hersteller]"
var HPLeistung="[Größe der Anlage] kWp"
var HPInbetrieb="[Installationsdatum]"
var HPAusricht="[Modulneigung und Ausrichtung]"
var BannerZeile1="[Kurzbez.Anlage]"
var BannerZeile2="4,5 kWp in 99999 Musterort"
var BannerZeile3="im Netz seit Januar 2008"
var BannerLink="www.solarlog-home.de/benutzer"
var StatusCodes = new Array(5)
var FehlerCodes = new Array(5)
StatusCodes[0] = "Standby: Initializing,Standby:  Detecting ISO,Standby: Detecting irradiation,Standby: Grid detecting,Starting,On-grid,On-grid: Power limit,On-grid: self derating,Shutdown: Fault,Shutdown: Command,Shutdown: OVGR,Shutdown: Communication disconnected,Shutdown: Power limit,Shutdown: manual startuo required,Shutdown: DC switch disconnected,Shutdown: rapid cutoff,Shutdown: input underpower,Grid scheduling cos(Phi)-P curve,Grid scheduling Q-U curve,Grid scheduling PF-U curve,Grid scheduling dry contact,Grid scheduling Q-P curve,Spot-check,Spot-checking,Inspecting,AFCI self-check,I-V scanning,DC input detection,Running off-grid charging,Standby no irradiation,Undefined"
FehlerCodes[0] = " ,High String Voltage,DC Arc Fault,String Reversed,PV String Backfeed,Abnormal String,AFCI Self-test Fault,SC between phase to PE,Power Grid Failure,Grid Undervoltage,Grid Overvoltage,Unbalanced Grid Voltage,Grid Overfrequency,Grid Underfrequency,Grid Frequency Instability,Output Overcurrent,Large DC of Output current,Abnormal Leakage Current,Abnormal Ground,Low Insulation Res,High Temperature,Abnormal Equipment,Upgrade Failed,License Expired,Abnormal Monitor Unit,High String V to Ground,Built-in PID abnormal,Power collector fault,Abnormal En storage dev,Active islanding,Passive islanding,Transient AC overvoltage,Abnormal PV module conf,External fan abnormal,Battery Reverse Connection,On/Off-grid con abnormal,PV String Loss,Internal Fan Abnormal,DC Protection Unit Abnormal,EL Unit Abnormal,Active Adj Ins Abnormal,Reactive Adj Ins Abnormal,CT Wiring Abnormal,DC Arc Fault,Undefined"
StatusCodes[1] = "Standby: Initializing,Standby:  Detecting ISO,Standby: Detecting irradiation,Standby: Grid detecting,Starting,On-grid,On-grid: Power limit,On-grid: self derating,Shutdown: Fault,Shutdown: Command,Shutdown: OVGR,Shutdown: Communication disconnected,Shutdown: Power limit,Shutdown: manual startuo required,Shutdown: DC switch disconnected,Shutdown: rapid cutoff,Shutdown: input underpower,Grid scheduling cos(Phi)-P curve,Grid scheduling Q-U curve,Grid scheduling PF-U curve,Grid scheduling dry contact,Grid scheduling Q-P curve,Spot-check,Spot-checking,Inspecting,AFCI self-check,I-V scanning,DC input detection,Running off-grid charging,Standby no irradiation,Undefined"
FehlerCodes[1] = " ,High String Voltage,DC Arc Fault,String Reversed,PV String Backfeed,Abnormal String,AFCI Self-test Fault,SC between phase to PE,Power Grid Failure,Grid Undervoltage,Grid Overvoltage,Unbalanced Grid Voltage,Grid Overfrequency,Grid Underfrequency,Grid Frequency Instability,Output Overcurrent,Large DC of Output current,Abnormal Leakage Current,Abnormal Ground,Low Insulation Res,High Temperature,Abnormal Equipment,Upgrade Failed,License Expired,Abnormal Monitor Unit,High String V to Ground,Built-in PID abnormal,Power collector fault,Abnormal En storage dev,Active islanding,Passive islanding,Transient AC overvoltage,Abnormal PV module conf,External fan abnormal,Battery Reverse Connection,On/Off-grid con abnormal,PV String Loss,Internal Fan Abnormal,DC Protection Unit Abnormal,EL Unit Abnormal,Active Adj Ins Abnormal,Reactive Adj Ins Abnormal,CT Wiring Abnormal,DC Arc Fault,Undefined"
StatusCodes[2] = "Off,Sleeping,Starting,Running,Throttled,Shutting Down,Fault,Standby,Undefined"
FehlerCodes[2] = " ,Ground fault,DC over volt,AC disconnect,DC disconnect,Grid disconnect,Cabinet open,Manual shutdown,Over temp,Over frequency,Under frequency,AC over volt,AC under volt,Blown string fuse,Under temp,Memory loss,HW test failure,Manufacturer alarm,Undefined"
StatusCodes[3] = "Off,Sleeping,Starting,Running,Throttled,Shutting Down,Fault,Standby,Undefined"
FehlerCodes[3] = " ,Ground fault,DC over volt,AC disconnect,DC disconnect,Grid disconnect,Cabinet open,Manual shutdown,Over temp,Over frequency,Under frequency,AC over volt,AC under volt,Blown string fuse,Under temp,Memory loss,HW test failure,Manufacturer alarm,Undefined"
StatusCodes[4] = " ,RUNNING,IDLE,UNDEFINED"
FehlerCodes[4] = " ,EXT.ALARM,UNDEFINED"
var Verguetung=4675
var Serialnr = 12345
var Firmware = "6.1.2 Build 165"
var FirmwareDate = "16.07.2024"
var WRTyp = "MULTIPROTOCOL"
var OEMTyp = 0
var SLTyp = "63"
var SLVer = 2
var SLHW = 12345
var SLBV = 4
var Intervall = 300
var SLDatum = "05.03.25"
var SLUhrzeit = "04:00:11"
var isTemp=true
var isOnline=true
var eventsHP=0
var exportDir=""
var Lang="DE"
var AnzahlGrp=0
var CFDatum = "14.01.25"
var CFUhrzeit = "18:21:01"
var SCB = false
var SCBIF1 = 0
var webMenuFull = 0
var IPlatform = 3
var DateFormat ="dd.mm.yy"
var TimeFormat ="HH:MM:ss"
var TimeFormatNoSec ="HH:MM"
var Currency ="€"
var CurrencySub ="Cent"
var CurrencyFirst ="0"
var ISOCode ="DE"
var DSTMode ="1"
var Dezimalseparator =","
var WeightUnit ="KG"
var DirectMarketing = 350
var AdamAvailable=0
var netProfile=0
var pmControlType=2
var pmReductionOnSerialType=0
var windinverters=0
var co2factor=700
